-- DEPRECATED SECURITY-SENSITIVE LEGACY SCRIPT
-- DO NOT RUN THIS FILE AGAIN.
-- Shyaka Cup production now uses approved-admin RLS and private player media.
-- Re-running the old version of this script could weaken security by granting broad
-- authenticated access or making player files public.
--
-- Current security rules are enforced in the live Supabase project and documented
-- in SECURITY.md. Use a reviewed migration for any future database change.
