-- SHYAKA CUP ENTEBBE — LIVE SCORES + REFEREE REPORTS
-- Run this once in Supabase SQL Editor.

-- Fixtures already store score + status.
-- The app now uses status = 'live' while a match is in progress.
-- No fixtures schema change is required.

create table if not exists public.referee_reports (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null unique references public.fixtures(id) on delete cascade,
  referee_name text not null,
  assistant_referee_1 text,
  assistant_referee_2 text,
  fourth_official text,
  kickoff_time text,
  final_score text,
  yellow_cards integer not null default 0,
  red_cards integer not null default 0,
  pitch_condition text,
  team_conduct text,
  incidents text,
  remarks text,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.referee_reports enable row level security;

drop policy if exists "Public reads published referee reports" on public.referee_reports;
create policy "Public reads published referee reports"
on public.referee_reports
for select
to anon
using (is_public = true);

drop policy if exists "Authenticated reads referee reports" on public.referee_reports;
create policy "Authenticated reads referee reports"
on public.referee_reports
for select
to authenticated
using (public.is_shyaka_admin() or is_public = true);

drop policy if exists "Approved admins manage referee reports" on public.referee_reports;
create policy "Approved admins manage referee reports"
on public.referee_reports
for all
to authenticated
using (public.is_shyaka_admin())
with check (public.is_shyaka_admin());

grant select on public.referee_reports to anon, authenticated;
grant insert, update, delete on public.referee_reports to authenticated;
grant usage, select on sequence public.referee_reports_id_seq to authenticated;
