-- SHYAKA CUP ENTEBBE 2026 — Tournament upgrade
-- Run once in Supabase SQL Editor. It is non-destructive to the existing players table.

create table if not exists public.fixtures (
  id bigint generated by default as identity primary key,
  match_no integer not null unique,
  match_date date not null,
  division text not null,
  home_team text not null,
  away_team text not null,
  venue text,
  match_time text,
  stage text,
  status text not null default 'scheduled' check (status in ('scheduled','completed','postponed','cancelled')),
  home_score integer,
  away_score integer,
  updated_at timestamptz default now()
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  fixture_id bigint references public.fixtures(id) on delete cascade,
  event_type text not null check (event_type in ('goal','assist','yellow_card','red_card','substitution','man_of_match')),
  team_name text,
  player_name text,
  minute integer,
  notes text,
  created_at timestamptz default now()
);

alter table public.fixtures enable row level security;
alter table public.match_events enable row level security;

drop policy if exists "Public can view fixtures" on public.fixtures;
create policy "Public can view fixtures" on public.fixtures for select to anon, authenticated using (true);
drop policy if exists "Admins can update fixtures" on public.fixtures;
create policy "Admins can update fixtures" on public.fixtures for update to authenticated using (true) with check (true);
drop policy if exists "Admins can insert fixtures" on public.fixtures;
create policy "Admins can insert fixtures" on public.fixtures for insert to authenticated with check (true);

drop policy if exists "Public can view match events" on public.match_events;
create policy "Public can view match events" on public.match_events for select to anon, authenticated using (true);
drop policy if exists "Admins can manage match events" on public.match_events;
create policy "Admins can manage match events" on public.match_events for all to authenticated using (true) with check (true);

insert into public.fixtures (match_no,match_date,division,home_team,away_team,venue,match_time,stage) values
(1,'2026-08-30','Kiwafu Ward','KIWAFU CENTRAL','LUGONJO','KIWAFU','4:00 PM','group'),
(2,'2026-09-03','Katabi Ward','MANYAGO 1','BUSAMBAGA','EBB SS','4:00 PM','group'),
(3,'2026-09-04','Central 2','VIRUS','BANGA NAKIWOGO','BANGA','4:00 PM','group'),
(4,'2026-09-05','Central 1','KITASA','BUGONGA','LVS','4:00 PM','group'),
(5,'2026-09-10','Kiwafu Ward','KIWAFU EAST','KITOORO','KIWAFU','4:00 PM','group'),
(6,'2026-09-11','Kigungu Ward','MISOLI','OLD ENTEBBE','KIGUNGU','4:00 PM','group'),
(7,'2026-09-16','Central 1','NAKASAMBA','KAKEKA','LVS','4:00 PM','group'),
(8,'2026-09-17','Katabi Ward','KITUBULU','NAMATE','KABIRA','4:00 PM','group'),
(9,'2026-09-17','Kigungu Ward','MAYANZI','KIGUNGU CENTRAL','KIGUNGU','4:00 PM','group'),
(10,'2026-09-18','Central 2','LUNYO EAST','LUNYO CENTRAL','POLICE','4:00 PM','group'),
(11,'2026-09-18','Kiwafu Ward','KIWAFU WEST','KIWAFU EAST','KIWAFU','4:00 PM','group'),
(12,'2026-09-23','Central 1','POST OFFICE','BUGONGA','LVS','4:00 PM','group'),
(13,'2026-09-24','Central 2','NSAMIZI','BANGA NAKIWOGO','POLICE','4:00 PM','group'),
(14,'2026-09-24','Kiwafu Ward','KITOORO','KIWAFU CENTRAL','KIWAFU','4:00 PM','group'),
(15,'2026-09-25','Katabi Ward','MANYAGO 2','BUSAMBAGA','EBB SS','4:00 PM','group'),
(16,'2026-09-30','Katabi Ward','NAMATE','MANYAGO 1','WORKS','4:00 PM','group'),
(17,'2026-10-01','Central 1','KAKEKA','KITASA','LVS','4:00 PM','group'),
(18,'2026-10-01','Kigungu Ward','OLD ENTEBBE','KIGUNGU CENTRAL','CAA','4:00 PM','group'),
(19,'2026-10-02','Central 2','LUNYO CENTRAL','VIRUS','POLICE','4:00 PM','group'),
(20,'2026-10-07','Central 2','LUNYO EAST','NSAMIZI','POLICE','4:00 PM','group'),
(21,'2026-10-08','Katabi Ward','KITUBULU','MANYAGO 2','KABIRA','4:00 PM','group'),
(22,'2026-10-08','Kiwafu Ward','KIWAFU WEST','LUGONJO','KIWAFU','4:00 PM','group'),
(23,'2026-10-09','Central 1','NAKASAMBA','POST OFFICE','LVS','4:00 PM','group'),
(24,'2026-10-14','Central 1','BUGONGA','KAKEKA','FTI','4:00 PM','group'),
(25,'2026-10-15','Central 2','BANGA NAKIWOGO','LUNYO CENTRAL','BANGA','4:00 PM','group'),
(26,'2026-10-15','Kigungu Ward','MISOLI','MAYANZI','KIGUNGU','4:00 PM','group'),
(27,'2026-10-16','Katabi Ward','BUSAMBAGA','NAMATE','KABIRA','4:00 PM','group'),
(28,'2026-10-16','Kiwafu Ward','KIWAFU CENTRAL','KIWAFU EAST','KIWAFU','4:00 PM','group'),
(29,'2026-10-21','Central 1','POST OFFICE','KAKEKA','LVS','4:00 PM','group'),
(30,'2026-10-21','Katabi Ward','MANYAGO 2','NAMATE','EBB SS','4:00 PM','group'),
(31,'2026-10-22','Kiwafu Ward','LUGONJO','KIWAFU EAST','KIWAFU','4:00 PM','group'),
(32,'2026-10-23','Central 2','NSAMIZI','LUNYO CENTRAL','POLICE','4:00 PM','group'),
(33,'2026-10-28','Central 2','LUNYO EAST','VIRUS','POLICE','4:00 PM','group'),
(34,'2026-10-29','Katabi Ward','KITUBULU','MANYAGO 1','KABIRA','4:00 PM','group'),
(35,'2026-10-29','Kigungu Ward','MAYANZI','OLD ENTEBBE','KIGUNGU','4:00 PM','group'),
(36,'2026-10-30','Central 1','NAKASAMBA','KITASA','LVS','4:00 PM','group'),
(37,'2026-10-30','Kiwafu Ward','KIWAFU WEST','KITOORO','KIWAFU','4:00 PM','group'),
(38,'2026-11-04','Central 1','KITASA','POST OFFICE','LVS','4:00 PM','group'),
(39,'2026-11-05','Central 2','VIRUS','NSAMIZI','BANGA','4:00 PM','group'),
(40,'2026-11-05','Kiwafu Ward','KITOORO','LUGONJO','KIWAFU','4:00 PM','group'),
(41,'2026-11-06','Katabi Ward','MANYAGO 1','MANYAGO 2','EBB SS','4:00 PM','group'),
(42,'2026-11-06','Kigungu Ward','KIGUNGU CENTRAL','MISOLI','KIGUNGU','4:00 PM','group'),
(43,'2026-11-11','Katabi Ward','BUSAMBAGA','KITUBULU','KABIRA','4:00 PM','group'),
(44,'2026-11-12','Central 1','BUGONGA','NAKASAMBA','FTI','4:00 PM','group'),
(45,'2026-11-13','Central 2','BANGA NAKIWOGO','LUNYO EAST','BANGA','4:00 PM','group'),
(46,'2026-11-13','Kiwafu Ward','KIWAFU CENTRAL','KIWAFU WEST','KIWAFU','4:00 PM','group'),
(47,'2026-11-19','Knockout (Div A)','TBD','TBD','TBD','TBD','1ST LEG QF (2)'),
(48,'2026-11-20','Knockout (Div A)','TBD','TBD','TBD','TBD','1ST LEG QF (1)'),
(49,'2026-11-26','Knockout (Div A)','TBD','TBD','TBD','TBD','2ND LEG QF (2)'),
(50,'2026-11-27','Knockout (Div A)','TBD','TBD','TBD','TBD','2ND LEG QF (1)'),
(51,'2026-12-03','Knockout (Div B)','TBD','TBD','TBD','TBD','1ST LEG SEMI'),
(52,'2026-12-04','Knockout (Div A)','TBD','TBD','TBD','TBD','1ST LEG SEMI'),
(53,'2026-12-10','Knockout (Div A)','TBD','TBD','TBD','TBD','2ND LEG SEMI'),
(54,'2026-12-11','Knockout (Div A)','TBD','TBD','TBD','TBD','2ND LEG SEMI'),
(55,'2026-12-18','Knockout (All Div)','TBD','TBD','TBD','TBD','3RD PLACE PLAYOFF'),
(56,'2026-12-20','Knockout (All Div)','TBD','TBD','TBD','TBD','FINAL')
on conflict (match_no) do update set
 match_date=excluded.match_date, division=excluded.division, home_team=excluded.home_team, away_team=excluded.away_team,
 venue=excluded.venue, match_time=excluded.match_time, stage=excluded.stage;
