-- SHYAKA CUP ENTEBBE 2026 — COMPLETE TOURNAMENT APP
-- Run once in Supabase SQL Editor after the earlier tournament SQL.
-- Safe to run again.

-- Team profiles
create table if not exists public.team_profiles (
  id bigint generated by default as identity primary key,
  team_name text not null unique,
  division text,
  coach text,
  captain text,
  logo_url text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Public news / announcements
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category text default 'News',
  published boolean not null default true,
  published_at timestamptz default now(),
  created_at timestamptz default now()
);

-- Public gallery
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  caption text,
  image_url text not null,
  created_at timestamptz default now()
);

alter table public.team_profiles enable row level security;
alter table public.news enable row level security;
alter table public.gallery enable row level security;

-- Public read policies
drop policy if exists "Public can view team profiles" on public.team_profiles;
create policy "Public can view team profiles" on public.team_profiles for select to anon, authenticated using (true);

drop policy if exists "Public can view published news" on public.news;
create policy "Public can view published news" on public.news for select to anon, authenticated using (published = true or auth.role() = 'authenticated');

drop policy if exists "Public can view gallery" on public.gallery;
create policy "Public can view gallery" on public.gallery for select to anon, authenticated using (true);

-- Admin management policies
drop policy if exists "Admins manage team profiles" on public.team_profiles;
create policy "Admins manage team profiles" on public.team_profiles for all to authenticated using (true) with check (true);

drop policy if exists "Admins manage news" on public.news;
create policy "Admins manage news" on public.news for all to authenticated using (true) with check (true);

drop policy if exists "Admins manage gallery" on public.gallery;
create policy "Admins manage gallery" on public.gallery for all to authenticated using (true) with check (true);

-- Ensure admins have full fixture management.
drop policy if exists "Admins can delete fixtures" on public.fixtures;
create policy "Admins can delete fixtures" on public.fixtures for delete to authenticated using (true);

-- Ensure authenticated admins can fully manage players.
drop policy if exists "Authenticated admins can update players" on public.players;
create policy "Authenticated admins can update players" on public.players for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated admins can delete players" on public.players;
create policy "Authenticated admins can delete players" on public.players for delete to authenticated using (true);

-- Storage permissions for player photos, licences and gallery images.
drop policy if exists "Authenticated admins can upload player files" on storage.objects;
create policy "Authenticated admins can upload player files" on storage.objects for insert to authenticated with check (bucket_id = 'player-files');

drop policy if exists "Authenticated admins can update player files" on storage.objects;
create policy "Authenticated admins can update player files" on storage.objects for update to authenticated using (bucket_id = 'player-files') with check (bucket_id = 'player-files');

drop policy if exists "Authenticated admins can delete player files" on storage.objects;
create policy "Authenticated admins can delete player files" on storage.objects for delete to authenticated using (bucket_id = 'player-files');

drop policy if exists "Public can read player files" on storage.objects;
create policy "Public can read player files" on storage.objects for select to public using (bucket_id = 'player-files');

-- Seed team profile rows for all teams in the official fixture.
insert into public.team_profiles (team_name, division) values
('KIWAFU CENTRAL','Kiwafu Ward'),('LUGONJO','Kiwafu Ward'),('KIWAFU EAST','Kiwafu Ward'),('KITOORO','Kiwafu Ward'),('KIWAFU WEST','Kiwafu Ward'),
('MANYAGO 1','Katabi Ward'),('BUSAMBAGA','Katabi Ward'),('KITUBULU','Katabi Ward'),('NAMATE','Katabi Ward'),('MANYAGO 2','Katabi Ward'),
('KITASA','Central 1'),('BUGONGA','Central 1'),('NAKASAMBA','Central 1'),('KAKEKA','Central 1'),('POST OFFICE','Central 1'),
('VIRUS','Central 2'),('BANGA NAKIWOGO','Central 2'),('LUNYO EAST','Central 2'),('LUNYO CENTRAL','Central 2'),('NSAMIZI','Central 2'),
('MISOLI','Kigungu Ward'),('OLD ENTEBBE','Kigungu Ward'),('MAYANZI','Kigungu Ward'),('KIGUNGU CENTRAL','Kigungu Ward')
on conflict (team_name) do update set division = excluded.division;
