const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function region(start,end){const a=html.indexOf(start),b=html.indexOf(end,a);assert(a>=0&&b>a);return html.slice(a,b);}
function node(tag='div'){const classes=new Set();return {tagName:tag.toUpperCase(),children:[],dataset:{},isConnected:true,hidden:false,classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)},setAttribute(){},replaceChildren(...kids){this.children=kids;},append(...kids){this.children.push(...kids);},prepend(k){this.children.unshift(k);}};}
function context(){let now=100000,calls=0;const nodes={};const c={console,Map,Promise,Date:{now:()=>now},setTimeout,clearTimeout,approvedAdmin:true,events:[],players:[],fixtures:[],villages:[],galleryItems:[],matchHighlights:[],newsItems:[],teamMeta:[],refereeReports:[],deletedPlayerNumbers:new Set(),window:{},crypto:require('node:crypto').webcrypto,esc:s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),$:id=>nodes[id]??=(node()),document:{createElement:node,createTextNode:s=>({textContent:s}),querySelectorAll:()=>[]},db:{storage:{from:()=>({createSignedUrl:async()=>{calls++;return {data:{signedUrl:'https://test.invalid/signed/'+calls}}}})}}};for(const name of ['initSelects','renderAll','renderAdminSummary','renderEventList','renderNews','renderGallery','renderLiveScores','renderMatchCentre','renderRefereeReports','renderAdminLists','renderAdminPlayerRowsFast','renderTeams'])c[name]=()=>{};vm.createContext(c);vm.runInContext(region('function playerMediaPath(','async function loadOnline()'),c);vm.runInContext(region('async function openLicenceViewer(','function fixtureStatusLabel('),c);return {c,nodes,advance:ms=>now+=ms,calls:()=>calls};}
test('600 players load paths without 1200 eager signing calls',async()=>{const {c,calls}=context();const rows=Array.from({length:600},(_,i)=>({id:i,photo_url:'photos/'+i,licence_url:'licenses/'+i}));c.db.from=table=>({select:()=>({order:async()=>({data:table==='players'?rows:[]}),then:resolve=>resolve({data:[]}),eq:()=>({order:async()=>({data:[]})})})});vm.runInContext(region('async function loadOnline()','function currentTeams('),c);await c.loadOnline();assert.equal(c.players.length,600);assert.equal(calls(),0);assert.equal(c.players[599].license,'licenses/599');});
test('admin player rows render before slower tournament requests finish',async()=>{const {c}=context();let earlyCount=0;const releases=[];const quick=new Set(['villages','deleted_players','players']);c.renderAdminPlayerRowsFast=()=>{earlyCount=c.players.length};c.db.from=table=>{const response={data:table==='villages'?[{id:1,name:'TEAM'}]:table==='players'?[{id:7,name:'Fast Player',player_number:'7',village_id:1}]:[],error:null};const promise=quick.has(table)?Promise.resolve(response):new Promise(resolve=>releases.push(()=>resolve(response)));const builder={select(){return builder},eq(){return builder},order(){return builder},then(resolve,reject){return promise.then(resolve,reject)}};return builder};vm.runInContext(region('async function loadOnline()','function currentTeams('),c);const pending=c.loadOnline();await new Promise(resolve=>setImmediate(resolve));assert.equal(earlyCount,1);releases.forEach(release=>release());await pending;assert.equal(c.players[0].village,'TEAM');});
test('same media request deduplicates, caches, then renews before expiry',async()=>{const {c,calls,advance}=context();const results=await Promise.all(Array.from({length:10},()=>c.signedPlayerMedia('licenses/1',300)));assert.equal(new Set(results).size,1);assert.equal(calls(),1);await c.signedPlayerMedia('licenses/1',300);assert.equal(calls(),1);advance(241000);await c.signedPlayerMedia('licenses/1',300);assert.equal(calls(),2);});
test('signing concurrency is bounded at four',async()=>{const {c}=context();let active=0,max=0;c.db.storage.from=()=>({createSignedUrl:async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,2));active--;return {data:{signedUrl:'signed'}}}});await Promise.all(Array.from({length:30},(_,i)=>c.signedPlayerMedia('photos/'+i)));assert.equal(max,4);});
test('public visitors cannot request private media',async()=>{const {c,calls}=context();c.approvedAdmin=false;assert.equal(await c.signedPlayerMedia('licenses/1'),'');await c.openLicenceViewer('licenses/1','Player');assert.equal(calls(),0);});
test('logout discards signing requests that were already in flight',async()=>{const {c}=context();let finish;c.db.storage.from=()=>({createSignedUrl:()=>new Promise(resolve=>finish=resolve)});const pending=c.signedPlayerMedia('licenses/1');c.approvedAdmin=false;c.clearPrivateMedia();finish({data:{signedUrl:'must-not-survive'}});assert.equal(await pending,'');});
test('apostrophe names use a callback and open the correct licence',async()=>{const {c,nodes}=context();await c.openPlayerProfile({name:"O'Connor",license:'licenses/1'});const button=nodes.profileLicence.children[0];assert.equal(typeof button.onclick,'function');await button.onclick();assert.equal(nodes.licenceViewerBody.children[0].src,'https://test.invalid/signed/1');assert.equal(nodes.licenceViewerTitle.textContent,"O'Connor — Player Licence");});
test('closing viewer while signing prevents late content injection',async()=>{const {c,nodes}=context();let finish;c.db.storage.from=()=>({createSignedUrl:()=>new Promise(resolve=>finish=resolve)});const pending=c.openLicenceViewer('licenses/1','Player');c.closeLicenceViewer();finish({data:{signedUrl:'late'}});await pending;assert.equal(nodes.licenceViewerBody.children.length,0);});
test('expired licence is renewed when reopened',async()=>{const {c,nodes,advance,calls}=context();await c.openLicenceViewer('licenses/a.pdf','Player');assert.equal(nodes.licenceViewerBody.children[0].tagName,'IFRAME');c.closeLicenceViewer();advance(301000);await c.openLicenceViewer('licenses/a.pdf','Player');assert.equal(calls(),2);assert.equal(nodes.licenceViewerBody.children[0].src,'https://test.invalid/signed/2');});
test('gallery uploads target gallery; player uploads keep private paths',async()=>{const {c}=context();const buckets=[];c.db.storage.from=b=>({upload:async()=>{buckets.push(b);return {}},getPublicUrl:p=>({data:{publicUrl:'https://test.invalid/'+b+'/'+p}})});vm.runInContext(region('async function uploadFile(','$(\'savePlayer\')'),c);const photo=await c.uploadFile({name:'photo.jpg'},'photos');const gallery=await c.uploadFile({name:'gallery.jpg'},'gallery','gallery');assert.deepEqual(buckets,['player-files','gallery']);assert.match(photo,/^photos\//);assert.match(gallery,/\/gallery\/gallery\//);});
test('legacy gallery recovery only copies gallery media and keeps originals',async()=>{const {c}=context();let downloaded=[],uploaded=[],removed=[];const original='https://test.invalid/storage/v1/object/public/player-files/gallery/photo.jpg';c.galleryItems=[{id:1,image_url:original},{id:2,image_url:'https://test.invalid/storage/v1/object/public/player-files/licenses/private.jpg'}];c.db.storage.from=b=>({download:async p=>{downloaded.push([b,p]);return {data:{type:'image/jpeg'}}},upload:async p=>{uploaded.push([b,p]);return {}},getPublicUrl:p=>({data:{publicUrl:'https://test.invalid/gallery/'+p}}),remove:async p=>{removed.push([b,p]);return {}}});c.db.from=()=>({update:()=>({eq:()=>({eq:()=>({select:async()=>({data:[{id:1}]})})})})});vm.runInContext(region('let galleryRepairInFlight=','function renderGallery()'),c);await c.repairLegacyGallery();assert.deepEqual(downloaded,[['player-files','gallery/photo.jpg']]);assert.equal(uploaded[0][0],'gallery');assert.equal(removed.length,0);assert.match(c.galleryItems[0].image_url,/\/gallery\/recovered\//);assert.match(c.galleryItems[1].image_url,/player-files\/licenses/);});
test('live refresh also updates Home, results, standings and totals',async()=>{const {c}=context();const rendered=[];c.db.from=()=>({select:()=>({order:async()=>({data:[]})})});for(const n of ['renderLiveScores','renderMatchCentre','renderHome','renderResults','renderStandings','renderStats'])c[n]=()=>rendered.push(n);vm.runInContext(region('async function refreshLiveOnly()','let shyakaLiveRefreshTimer='),c);await c.refreshLiveOnly();assert.deepEqual(rendered,['renderLiveScores','renderMatchCentre','renderHome','renderResults','renderStandings','renderStats']);});
