const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function harness(){
 const buckets=new Map(),handlers={};let now=10000000,fetcher=async()=>new Response('network');
 const key=r=>typeof r==='string'?r:r.url;
 function bucket(name){if(!buckets.has(name)){const map=new Map();buckets.set(name,{match:async r=>map.get(key(r))?.clone(),put:async(r,v)=>{map.set(key(r),v.clone())},delete:async r=>map.delete(key(r)),keys:async()=>[...map.keys()],addAll:async()=>{}})}return buckets.get(name)}
 const c={URL,Headers,Request,Response,AbortController,setTimeout:(fn,ms)=>setTimeout(fn,Math.min(ms,5)),clearTimeout,Date:{now:()=>now},fetch:(...a)=>fetcher(...a),self:{location:{origin:'https://shyakacup.com'},addEventListener:(k,f)=>handlers[k]=f,clients:{claim:async()=>{}},skipWaiting:async()=>{}},caches:{open:async name=>bucket(name),keys:async()=>[...buckets.keys()],delete:async name=>buckets.delete(name)}};
 vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),c);
 function dispatch(url,{mode='cors',destination='',method='GET',headers={}}={}){const request=new Request(url,{method,headers});Object.defineProperties(request,{mode:{value:mode},destination:{value:destination}});let promise;handlers.fetch({request,respondWith:p=>promise=p});return promise}
 return {c,bucket,handlers,dispatch,fetch:f=>fetcher=f,advance:ms=>now+=ms,buckets};
}
test('503 navigation returns cached app shell',async()=>{const h=harness();await h.bucket('shyaka-cup-stadium-v4').put('/index.html',new Response('saved app'));h.fetch(async()=>new Response('down',{status:503}));assert.equal(await (await h.dispatch('https://shyakacup.com/',{mode:'navigate'})).text(),'saved app')});
test('hanging navigation falls back within timeout',async()=>{const h=harness();await h.bucket('shyaka-cup-stadium-v4').put('/index.html',new Response('saved'));h.fetch(()=>new Promise(()=>{}));assert.equal(await(await h.dispatch('https://shyakacup.com/',{mode:'navigate'})).text(),'saved')});
test('cold outage has a clear unavailable response',async()=>{const h=harness();h.fetch(async()=>{throw Error('offline')});const r=await h.dispatch('https://shyakacup.com/',{mode:'navigate'});assert.equal(r.status,503);assert.match(await r.text(),/Connect once/)});
test('private, signed, API and untrusted-origin responses are never intercepted',()=>{const h=harness();for(const url of ['https://shyakacup.com/api/players','https://shyakacup.com/player-files/licenses/a.jpg','https://other.test/storage/v1/object/public/gallery/a.jpg','https://tjabrrvfxlyqkhzhtnyb.supabase.co/storage/v1/object/sign/player-files/a.jpg','https://tjabrrvfxlyqkhzhtnyb.supabase.co/storage/v1/object/public/gallery/a.jpg?token=x'])assert.equal(h.dispatch(url,{destination:'image'}),undefined);assert.equal(h.dispatch('https://tjabrrvfxlyqkhzhtnyb.supabase.co/storage/v1/object/public/gallery/a.jpg',{destination:'image',headers:{authorization:'Bearer private'}}),undefined)});
const gallery='https://tjabrrvfxlyqkhzhtnyb.supabase.co/storage/v1/object/public/gallery/';
test('gallery replacement refreshes; a 404 removes withdrawn cached images',async()=>{const h=harness();h.fetch(async()=>new Response('first',{headers:{'content-type':'image/jpeg'}}));await h.dispatch(gallery+'a.jpg',{destination:'image'});h.fetch(async()=>new Response('replacement',{headers:{'content-type':'image/jpeg'}}));assert.equal(await(await h.dispatch(gallery+'a.jpg',{destination:'image'})).text(),'replacement');h.fetch(async()=>new Response('gone',{status:404}));await h.dispatch(gallery+'a.jpg',{destination:'image'});assert.equal((await h.bucket('shyaka-cup-public-media-v2').keys()).length,0)});
test('gallery fallback expires after 24h and removes persistent data',async()=>{const h=harness();h.fetch(async()=>new Response('photo',{headers:{'content-type':'image/jpeg'}}));await h.dispatch(gallery+'a.jpg',{destination:'image'});h.fetch(async()=>{throw Error('offline')});assert.equal(await(await h.dispatch(gallery+'a.jpg',{destination:'image'})).text(),'photo');h.advance(86400000);await assert.rejects(h.dispatch(gallery+'a.jpg',{destination:'image'}));assert.equal((await h.bucket('shyaka-cup-public-media-v2').keys()).length,0)});
test('simultaneous image writes stay within forty entries',async()=>{const h=harness();h.fetch(async()=>new Response('photo',{headers:{'content-type':'image/jpeg'}}));await Promise.all(Array.from({length:45},(_,i)=>h.dispatch(gallery+i+'.jpg',{destination:'image'})));assert.equal((await h.bucket('shyaka-cup-public-media-v2').keys()).length,40)});
test('oversized gallery image is displayed but not persisted',async()=>{const h=harness();h.fetch(async()=>new Response(new Uint8Array(2*1024*1024+1),{headers:{'content-type':'image/jpeg'}}));assert.equal((await h.dispatch(gallery+'big.jpg',{destination:'image'})).status,200);assert.equal((await h.bucket('shyaka-cup-public-media-v2').keys()).length,0)});
test('activation removes old Shyaka caches and preserves other applications',async()=>{const h=harness();h.bucket('shyaka-cup-public-media-v1');h.bucket('another-app');let work;h.handlers.activate({waitUntil:p=>work=p});await work;assert.equal(h.buckets.has('shyaka-cup-public-media-v1'),false);assert.equal(h.buckets.has('another-app'),true)});
