const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function harness({hidden=false,online=true,stored=null,blocked=false}={}){
 const calls=[],listeners={};let section='home',observer,tick;let time=100000;
 const context={window:{SHYAKA_SUPABASE_URL:'https://test.supabase.co',SHYAKA_SUPABASE_ANON_KEY:'anon',addEventListener:(k,f)=>listeners[k]=f},location:{hostname:'shyakacup.com'},document:{hidden,querySelector:q=>q==='.view.active'?{id:'view-'+section}:null,querySelectorAll:()=>[{}],getElementById:()=>null,addEventListener:(k,f)=>listeners[k]=f},navigator:{onLine:online},localStorage:{getItem:()=>{if(blocked)throw Error('blocked');return stored},setItem:(k,v)=>stored=v},crypto:{randomUUID:()=> '11111111-1111-4111-8111-111111111111'},MutationObserver:class{constructor(f){observer=f}observe(){}},setInterval:f=>tick=f,Date:{now:()=>time},AbortSignal:{timeout:()=>null},fetch:async(u,o)=>{calls.push(JSON.parse(o.body));return{ok:true}},approvedAdmin:false};
 vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../visitors.js'),'utf8'),context);
 return{calls,context,listeners,tick:()=>tick(),view:s=>{section=s;observer()},advance:()=>time+=60001,flush:()=>new Promise(setImmediate)};
}
test('same browser heartbeat is throttled; section navigation records same device',async()=>{const h=harness();await h.flush();assert.equal(h.calls.length,1);h.tick();await h.flush();assert.equal(h.calls.length,1);h.view('players');await h.flush();assert.equal(h.calls.length,2);assert.equal(h.calls[0].device,h.calls[1].device);h.advance();h.tick();await h.flush();assert.equal(h.calls.length,3)});
test('hidden, offline and storage-blocked clients do not send activity',async()=>{for(const opts of [{hidden:true},{online:false},{blocked:true}]){const h=harness(opts);await h.flush();assert.equal(h.calls.length,0)}});
test('returning to a visible app resumes heartbeat; unrecognized sections are ignored',async()=>{const h=harness({hidden:true});h.context.document.hidden=false;h.listeners.visibilitychange();await h.flush();assert.equal(h.calls.length,1);h.view('admin');await h.flush();assert.equal(h.calls.length,1)});
